import type {
  Ingredient,
  SKU,
  InnovationProject,
  CategoryConfig,
} from '../types.js';

// ============================================================
// SHAMPOO INGREDIENT LIBRARY — 40 ingredients
// ============================================================

const SHAMPOO_INGREDIENTS: Ingredient[] = [
  // ── Surfactants (1-6) ────────────────────────────────────
  {
    name: 'Sodium Laureth Sulfate',
    tradeName: 'SLES',
    inci: 'Sodium Laureth Sulfate',
    category: 'Surfactant',
    supplier: 'BASF',
    costPerKg: 2,
    properties: { usageMin: 8, usageMax: 15 },
    description: 'Primary anionic surfactant, excellent foaming.',
  },
  {
    name: 'Cocamidopropyl Betaine',
    inci: 'Cocamidopropyl Betaine',
    category: 'Surfactant',
    supplier: 'Colonial Chemical',
    costPerKg: 4,
    properties: { usageMin: 3, usageMax: 8 },
    description: 'Amphoteric co-surfactant, foam booster, mildness.',
  },
  {
    name: 'Sodium Cocoyl Isethionate',
    tradeName: 'SCI',
    inci: 'Sodium Cocoyl Isethionate',
    category: 'Surfactant',
    supplier: 'Innospec',
    costPerKg: 8,
    properties: { usageMin: 5, usageMax: 15 },
    description: 'Sulfate-free primary surfactant, very mild.',
  },
  {
    name: 'Decyl Glucoside',
    inci: 'Decyl Glucoside',
    category: 'Surfactant',
    supplier: 'BASF',
    costPerKg: 4,
    properties: { usageMin: 3, usageMax: 10 },
    description: 'Non-ionic, plant-derived, gentle cleanser.',
  },
  {
    name: 'Sodium Lauroyl Sarcosinate',
    inci: 'Sodium Lauroyl Sarcosinate',
    category: 'Surfactant',
    supplier: 'Croda',
    costPerKg: 7,
    properties: { usageMin: 2, usageMax: 6 },
    description: 'Amino acid-based surfactant, mild and conditioning.',
  },
  {
    name: 'Disodium Laureth Sulfosuccinate',
    inci: 'Disodium Laureth Sulfosuccinate',
    category: 'Surfactant',
    supplier: 'Stepan',
    costPerKg: 6,
    properties: { usageMin: 2, usageMax: 8 },
    description: 'Very mild anionic surfactant for baby/sensitive formulas.',
  },

  // ── Conditioning Agents (7-12) ──────────────────────────
  {
    name: 'Dimethicone',
    inci: 'Dimethicone',
    category: 'Humectant',
    supplier: 'Dow Corning',
    costPerKg: 6,
    properties: { usageMin: 0.5, usageMax: 3 },
    description: 'Silicone conditioner, adds shine and smoothness.',
  },
  {
    name: 'Cetrimonium Chloride',
    inci: 'Cetrimonium Chloride',
    category: 'Active Ingredient',
    supplier: 'Evonik',
    costPerKg: 6,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Cationic conditioner, detangling agent.',
  },
  {
    name: 'Behentrimonium Methosulfate',
    inci: 'Behentrimonium Methosulfate',
    category: 'Active Ingredient',
    supplier: 'Croda',
    costPerKg: 12,
    properties: { usageMin: 1, usageMax: 3 },
    description: 'Gentle quaternary conditioning agent.',
  },
  {
    name: 'Polyquaternium-10',
    inci: 'Polyquaternium-10',
    category: 'Active Ingredient',
    supplier: 'Ashland',
    costPerKg: 15,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Film-forming conditioning polymer.',
  },
  {
    name: 'Guar Hydroxypropyltrimonium Chloride',
    inci: 'Guar Hydroxypropyltrimonium Chloride',
    category: 'Active Ingredient',
    supplier: 'Solvay',
    costPerKg: 10,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Natural-origin conditioning polymer for sulfate-free systems.',
  },
  {
    name: 'Panthenol',
    tradeName: 'Pro-Vitamin B5',
    inci: 'Panthenol',
    category: 'Active Ingredient',
    supplier: 'DSM',
    costPerKg: 13,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Hair strengthening, moisture retention.',
  },

  // ── Humectants / Emollients (13-18) ─────────────────────
  {
    name: 'Glycerin',
    inci: 'Glycerin',
    category: 'Humectant',
    supplier: 'P&G Chemicals',
    costPerKg: 1,
    properties: { usageMin: 1, usageMax: 5 },
    description: 'Humectant, adds moisture.',
  },
  {
    name: 'Coconut Oil',
    inci: 'Cocos Nucifera Oil',
    category: 'Natural Extract',
    supplier: 'AAK',
    costPerKg: 3,
    properties: { usageMin: 0.5, usageMax: 3 },
    description: 'Hair penetration, moisture seal.',
  },
  {
    name: 'Argan Oil',
    inci: 'Argania Spinosa Kernel Oil',
    category: 'Natural Extract',
    supplier: 'BASF',
    costPerKg: 60,
    properties: { usageMin: 0.1, usageMax: 1 },
    description: 'Premium conditioning oil, shine and repair.',
  },
  {
    name: 'Shea Butter',
    inci: 'Butyrospermum Parkii Butter',
    category: 'Natural Extract',
    supplier: 'AAK',
    costPerKg: 8,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Rich emollient, moisture and manageability.',
  },
  {
    name: 'Hydrolyzed Keratin',
    inci: 'Hydrolyzed Keratin',
    category: 'Active Ingredient',
    supplier: 'Croda',
    costPerKg: 35,
    properties: { usageMin: 0.1, usageMax: 1 },
    description: 'Protein repair, strengthens damaged hair.',
  },
  {
    name: 'Propylene Glycol',
    inci: 'Propylene Glycol',
    category: 'Humectant',
    supplier: 'Dow Chemical',
    costPerKg: 2,
    properties: { usageMin: 1, usageMax: 5 },
    description: 'Humectant and solvent.',
  },

  // ── Thickeners / Viscosity (19-22) ──────────────────────
  {
    name: 'Sodium Chloride',
    inci: 'Sodium Chloride',
    category: 'Binder / Thickener',
    supplier: 'Morton Salt',
    costPerKg: 1,
    properties: { usageMin: 0.5, usageMax: 3 },
    description: 'Viscosity builder for SLES-based systems.',
  },
  {
    name: 'Carbomer',
    inci: 'Carbomer',
    category: 'Binder / Thickener',
    supplier: 'Lubrizol',
    costPerKg: 18,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Synthetic thickener for sulfate-free systems.',
  },
  {
    name: 'Xanthan Gum',
    inci: 'Xanthan Gum',
    category: 'Binder / Thickener',
    supplier: 'CP Kelco',
    costPerKg: 4,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Natural thickener, suspending agent.',
  },
  {
    name: 'Hydroxyethylcellulose',
    inci: 'Hydroxyethylcellulose',
    category: 'Binder / Thickener',
    supplier: 'Ashland',
    costPerKg: 6,
    properties: { usageMin: 0.3, usageMax: 1 },
    description: 'Non-ionic thickener, clear systems.',
  },

  // ── Actives / Specialty (23-30) ─────────────────────────
  {
    name: 'Zinc Pyrithione',
    tradeName: 'ZPT',
    inci: 'Zinc Pyrithione',
    category: 'Active Ingredient',
    supplier: 'Lonza',
    costPerKg: 30,
    properties: { usageMin: 0.5, usageMax: 2 },
    regulatoryNotes: 'OTC drug active for dandruff (1-2%). FDA monograph.',
    description: 'Anti-dandruff active, broad-spectrum antifungal.',
  },
  {
    name: 'Ketoconazole',
    inci: 'Ketoconazole',
    category: 'Active Ingredient',
    supplier: 'Hetero Drugs',
    costPerKg: 110,
    properties: { usageMin: 1, usageMax: 2 },
    regulatoryNotes: 'Prescription in some markets, OTC at 1% in others.',
    description: 'Potent antifungal for severe dandruff.',
  },
  {
    name: 'Salicylic Acid',
    inci: 'Salicylic Acid',
    category: 'Active Ingredient',
    supplier: 'Alfa Aesar',
    costPerKg: 10,
    properties: { usageMin: 1, usageMax: 3 },
    regulatoryNotes: 'OTC drug active for scalp psoriasis (2-3%).',
    description: 'Exfoliant, anti-dandruff, scalp treatment.',
  },
  {
    name: 'Biotin',
    tradeName: 'Vitamin B7',
    inci: 'Biotin',
    category: 'Active Ingredient',
    supplier: 'DSM',
    costPerKg: 140,
    properties: { usageMin: 0.01, usageMax: 0.1 },
    description: 'Hair growth and strength claims.',
  },
  {
    name: 'Caffeine',
    inci: 'Caffeine',
    category: 'Active Ingredient',
    supplier: 'BASF',
    costPerKg: 15,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Scalp stimulation, hair growth support.',
  },
  {
    name: 'Tea Tree Oil',
    inci: 'Melaleuca Alternifolia Leaf Oil',
    category: 'Natural Extract',
    supplier: 'Australian Botanical Products',
    costPerKg: 30,
    properties: { usageMin: 0.2, usageMax: 1 },
    description: 'Natural antiseptic, scalp health.',
  },
  {
    name: 'Niacinamide',
    tradeName: 'Vitamin B3',
    inci: 'Niacinamide',
    category: 'Active Ingredient',
    supplier: 'Lonza',
    costPerKg: 20,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Scalp barrier repair, sebum regulation.',
  },
  {
    name: 'Menthol',
    inci: 'Menthol',
    category: 'Active Ingredient',
    supplier: 'Symrise',
    costPerKg: 12,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Cooling sensation, refreshing scalp feel.',
  },

  // ── Preservatives (31-33) ───────────────────────────────
  {
    name: 'Phenoxyethanol',
    inci: 'Phenoxyethanol',
    category: 'Preservative',
    supplier: 'Schülke',
    costPerKg: 8,
    properties: { usageMin: 0.5, usageMax: 1 },
    description: 'Broad-spectrum preservative.',
  },
  {
    name: 'Sodium Benzoate',
    inci: 'Sodium Benzoate',
    category: 'Preservative',
    supplier: 'Emerald Kalama',
    costPerKg: 4,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Preservative, effective at low pH.',
  },
  {
    name: 'Potassium Sorbate',
    inci: 'Potassium Sorbate',
    category: 'Preservative',
    supplier: 'Celanese',
    costPerKg: 5,
    properties: { usageMin: 0.1, usageMax: 0.3 },
    description: 'Natural-compatible preservative.',
  },

  // ── Fragrances / Sensory (34-36) ────────────────────────
  {
    name: 'Fragrance (Fresh Ocean)',
    inci: 'Parfum',
    category: 'Flavor / Sweetener',
    supplier: 'Givaudan',
    costPerKg: 40,
    properties: { usageMin: 0.3, usageMax: 1 },
    description: 'Clean, fresh marine-inspired scent.',
  },
  {
    name: 'Fragrance (Coconut Vanilla)',
    inci: 'Parfum',
    category: 'Flavor / Sweetener',
    supplier: 'Firmenich',
    costPerKg: 35,
    properties: { usageMin: 0.3, usageMax: 1 },
    description: 'Tropical, sweet, spa-like scent.',
  },
  {
    name: 'Fragrance (Herbal Mint)',
    inci: 'Parfum',
    category: 'Flavor / Sweetener',
    supplier: 'IFF',
    costPerKg: 38,
    properties: { usageMin: 0.3, usageMax: 1 },
    description: 'Herbal and refreshing, rosemary-mint.',
  },

  // ── pH / Color / Solvent (37-40) ────────────────────────
  {
    name: 'Citric Acid',
    inci: 'Citric Acid',
    category: 'pH Adjuster',
    supplier: 'ADM',
    costPerKg: 2,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'pH adjuster to 5.0-5.5 optimal for hair.',
  },
  {
    name: 'Water',
    tradeName: 'Aqua',
    inci: 'Aqua',
    category: 'Solvent',
    supplier: 'N/A',
    costPerKg: 1,
    properties: { usageMin: 50, usageMax: 75 },
    description: 'Continuous phase / solvent.',
  },
  {
    name: 'D&C Yellow No. 10',
    inci: 'CI 47005',
    category: 'Colorant',
    supplier: 'Sensient',
    costPerKg: 35,
    properties: { usageMin: 0.001, usageMax: 0.01 },
    description: 'Yellow colorant for golden shampoo.',
  },
  {
    name: 'Ext. D&C Violet No. 2',
    inci: 'CI 60730',
    category: 'Colorant',
    supplier: 'Sensient',
    costPerKg: 45,
    properties: { usageMin: 0.001, usageMax: 0.005 },
    description: 'Purple/violet toning for blonde shampoos.',
  },
];

// ============================================================
// SHAMPOO SKU LIBRARY — 8 formulations
// ============================================================

const SHAMPOO_SKUS: SKU[] = [
  {
    name: 'CleanWave Daily Moisture 12oz',
    code: 'CW-DM-12',
    targetDemographic: 'General adult, all hair types',
    targetGeo: 'North America',
    positioningStatement: 'Everyday clean with lasting moisture',
    formulation: [
      { ingredientName: 'Water', percentageW: 62, role: 'Solvent' },
      { ingredientName: 'Sodium Laureth Sulfate', percentageW: 12, role: 'Primary surfactant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 5, role: 'Co-surfactant' },
      { ingredientName: 'Glycerin', percentageW: 3, role: 'Humectant' },
      { ingredientName: 'Sodium Chloride', percentageW: 2, role: 'Viscosity builder' },
      { ingredientName: 'Dimethicone', percentageW: 1.5, role: 'Conditioning' },
      { ingredientName: 'Propylene Glycol', percentageW: 4, role: 'Humectant' },
      { ingredientName: 'Polyquaternium-10', percentageW: 0.3, role: 'Conditioning polymer' },
      { ingredientName: 'Panthenol', percentageW: 1, role: 'Strengthening' },
      { ingredientName: 'Fragrance (Fresh Ocean)', percentageW: 0.5, role: 'Fragrance' },
      { ingredientName: 'Coconut Oil', percentageW: 1, role: 'Emollient' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.8, role: 'Preservative' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Citric Acid', percentageW: 0.3, role: 'pH adjuster' },
      { ingredientName: 'Hydroxyethylcellulose', percentageW: 0.3, role: 'Thickener' },
      { ingredientName: 'D&C Yellow No. 10', percentageW: 0.003, role: 'Colorant' },
      { ingredientName: 'Guar Hydroxypropyltrimonium Chloride', percentageW: 0.2, role: 'Conditioning' },
      { ingredientName: 'Sodium Lauroyl Sarcosinate', percentageW: 5.797, role: 'Co-surfactant' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 300, unit: 'RPM', range: { min: 200, max: 500 } },
      { name: 'Temperature', value: 40, unit: '°C', range: { min: 35, max: 50 } },
      { name: 'Mixing Time', value: 30, unit: 'minutes', range: { min: 20, max: 45 } },
    ],
    outcomes: [
      { name: 'Foam Volume', value: 280, unit: 'mL', target: { min: 250 }, higherIsBetter: true },
      { name: 'Viscosity', value: 8000, unit: 'cP', target: { min: 5000, max: 12000 } },
      { name: 'pH', value: 5.5, unit: '', target: { min: 5.0, max: 6.0 } },
      { name: 'Flash Lather Score', value: 8.0, unit: '/10', higherIsBetter: true },
      { name: 'Wet Combing Force Reduction', value: 35, unit: '%', higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.38,
    retailPrice: 5.99,
  },
  {
    name: 'CleanWave Anti-Dandruff ZPT 12oz',
    code: 'CW-AD-12',
    targetDemographic: 'Adults with dandruff/flaking',
    targetGeo: 'Global',
    positioningStatement: 'Clinically proven dandruff control',
    formulation: [
      { ingredientName: 'Water', percentageW: 60, role: 'Solvent' },
      { ingredientName: 'Sodium Laureth Sulfate', percentageW: 12, role: 'Primary surfactant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 5, role: 'Co-surfactant' },
      { ingredientName: 'Zinc Pyrithione', percentageW: 1.5, role: 'Anti-dandruff active' },
      { ingredientName: 'Glycerin', percentageW: 2, role: 'Humectant' },
      { ingredientName: 'Dimethicone', percentageW: 1, role: 'Conditioning' },
      { ingredientName: 'Sodium Chloride', percentageW: 2.5, role: 'Viscosity builder' },
      { ingredientName: 'Menthol', percentageW: 0.3, role: 'Cooling sensation' },
      { ingredientName: 'Polyquaternium-10', percentageW: 0.2, role: 'Conditioning polymer' },
      { ingredientName: 'Fragrance (Herbal Mint)', percentageW: 0.6, role: 'Fragrance' },
      { ingredientName: 'Propylene Glycol', percentageW: 6.5, role: 'Solvent' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.8, role: 'Preservative' },
      { ingredientName: 'Citric Acid', percentageW: 0.3, role: 'pH adjuster' },
      { ingredientName: 'Hydroxyethylcellulose', percentageW: 0.3, role: 'Thickener' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.2, role: 'Suspending agent' },
      { ingredientName: 'Panthenol', percentageW: 0.5, role: 'Scalp soothing' },
      { ingredientName: 'Niacinamide', percentageW: 1, role: 'Barrier repair' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Tea Tree Oil', percentageW: 0.5, role: 'Natural antiseptic' },
      { ingredientName: 'Guar Hydroxypropyltrimonium Chloride', percentageW: 0.2, role: 'Conditioning' },
      { ingredientName: 'Sodium Lauroyl Sarcosinate', percentageW: 4.3, role: 'Mild co-surfactant' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 400, unit: 'RPM', range: { min: 300, max: 600 } },
      { name: 'Temperature', value: 35, unit: '°C', range: { min: 30, max: 45 } },
      { name: 'Mixing Time', value: 40, unit: 'minutes', range: { min: 30, max: 55 } },
    ],
    outcomes: [
      { name: 'Foam Volume', value: 250, unit: 'mL', target: { min: 220 }, higherIsBetter: true },
      { name: 'Viscosity', value: 7500, unit: 'cP', target: { min: 5000, max: 10000 } },
      { name: 'pH', value: 5.3, unit: '', target: { min: 5.0, max: 5.8 } },
      { name: 'Dandruff Reduction', value: 75, unit: '%', target: { min: 50 }, higherIsBetter: true },
      { name: 'Scalp Irritation Score', value: 2.0, unit: '/10', target: { max: 3 } },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.52,
    retailPrice: 7.99,
  },
  {
    name: 'CleanWave Sulfate-Free Gentle 10oz',
    code: 'CW-SF-10',
    targetDemographic: 'Color-treated & sensitive scalps',
    targetGeo: 'North America, Europe',
    positioningStatement: 'Color-safe clean without compromise',
    formulation: [
      { ingredientName: 'Water', percentageW: 58, role: 'Solvent' },
      { ingredientName: 'Sodium Cocoyl Isethionate', percentageW: 10, role: 'Primary surfactant' },
      { ingredientName: 'Decyl Glucoside', percentageW: 5, role: 'Co-surfactant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 4, role: 'Foam booster' },
      { ingredientName: 'Glycerin', percentageW: 3, role: 'Humectant' },
      { ingredientName: 'Carbomer', percentageW: 0.3, role: 'Thickener' },
      { ingredientName: 'Argan Oil', percentageW: 0.5, role: 'Premium conditioning' },
      { ingredientName: 'Hydrolyzed Keratin', percentageW: 0.5, role: 'Protein repair' },
      { ingredientName: 'Guar Hydroxypropyltrimonium Chloride', percentageW: 0.3, role: 'Conditioning' },
      { ingredientName: 'Panthenol', percentageW: 1, role: 'Strengthening' },
      { ingredientName: 'Fragrance (Coconut Vanilla)', percentageW: 0.5, role: 'Fragrance' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.8, role: 'Preservative' },
      { ingredientName: 'Potassium Sorbate', percentageW: 0.2, role: 'Preservative' },
      { ingredientName: 'Citric Acid', percentageW: 0.3, role: 'pH adjuster' },
      { ingredientName: 'Shea Butter', percentageW: 1, role: 'Emollient' },
      { ingredientName: 'Propylene Glycol', percentageW: 14.6, role: 'Solvent / humectant' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 250, unit: 'RPM', range: { min: 200, max: 400 } },
      { name: 'Temperature', value: 45, unit: '°C', range: { min: 40, max: 55 } },
      { name: 'Mixing Time', value: 35, unit: 'minutes', range: { min: 25, max: 50 } },
    ],
    outcomes: [
      { name: 'Foam Volume', value: 200, unit: 'mL', target: { min: 170 }, higherIsBetter: true },
      { name: 'Viscosity', value: 6000, unit: 'cP', target: { min: 4000, max: 8000 } },
      { name: 'pH', value: 5.2, unit: '', target: { min: 4.8, max: 5.5 } },
      { name: 'Color Retention', value: 92, unit: '%', target: { min: 85 }, higherIsBetter: true },
      { name: 'Wet Combing Force Reduction', value: 45, unit: '%', higherIsBetter: true },
      { name: 'Shelf Stability', value: 18, unit: 'months', target: { min: 12 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.85,
    retailPrice: 11.99,
  },
  {
    name: 'CleanWave Keratin Repair 10oz',
    code: 'CW-KR-10',
    targetDemographic: 'Damaged/chemically-treated hair',
    targetGeo: 'Global',
    positioningStatement: 'Bond repair for visibly stronger hair',
    formulation: [
      { ingredientName: 'Water', percentageW: 59, role: 'Solvent' },
      { ingredientName: 'Sodium Laureth Sulfate', percentageW: 10, role: 'Primary surfactant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 5, role: 'Co-surfactant' },
      { ingredientName: 'Hydrolyzed Keratin', percentageW: 0.8, role: 'Protein repair' },
      { ingredientName: 'Dimethicone', percentageW: 2, role: 'Smoothing' },
      { ingredientName: 'Behentrimonium Methosulfate', percentageW: 1.5, role: 'Deep conditioning' },
      { ingredientName: 'Panthenol', percentageW: 1.5, role: 'Strengthening' },
      { ingredientName: 'Glycerin', percentageW: 3, role: 'Humectant' },
      { ingredientName: 'Sodium Chloride', percentageW: 1.5, role: 'Viscosity builder' },
      { ingredientName: 'Argan Oil', percentageW: 0.3, role: 'Shine' },
      { ingredientName: 'Coconut Oil', percentageW: 1, role: 'Penetrating oil' },
      { ingredientName: 'Polyquaternium-10', percentageW: 0.3, role: 'Film-forming' },
      { ingredientName: 'Fragrance (Coconut Vanilla)', percentageW: 0.6, role: 'Fragrance' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.8, role: 'Preservative' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Citric Acid', percentageW: 0.3, role: 'pH adjuster' },
      { ingredientName: 'Propylene Glycol', percentageW: 11.1, role: 'Solvent' },
      { ingredientName: 'Biotin', percentageW: 0.02, role: 'Hair growth' },
      { ingredientName: 'D&C Yellow No. 10', percentageW: 0.002, role: 'Colorant' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.978, role: 'Thickener' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 350, unit: 'RPM', range: { min: 250, max: 500 } },
      { name: 'Temperature', value: 45, unit: '°C', range: { min: 40, max: 55 } },
      { name: 'Mixing Time', value: 40, unit: 'minutes', range: { min: 30, max: 55 } },
    ],
    outcomes: [
      { name: 'Foam Volume', value: 240, unit: 'mL', target: { min: 200 }, higherIsBetter: true },
      { name: 'Viscosity', value: 7000, unit: 'cP', target: { min: 5000, max: 9000 } },
      { name: 'pH', value: 5.5, unit: '', target: { min: 5.0, max: 6.0 } },
      { name: 'Tensile Strength Improvement', value: 22, unit: '%', higherIsBetter: true },
      { name: 'Wet Combing Force Reduction', value: 50, unit: '%', higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.68,
    retailPrice: 9.99,
  },
];

// ============================================================
// SHAMPOO PROJECTS — 3 projects
// ============================================================

const SHAMPOO_PROJECTS: InnovationProject[] = [
  {
    name: 'Sulfate-Free Daily Shampoo',
    type: 'ingredient_substitution',
    description:
      'Reformulate CleanWave Daily Moisture to be sulfate-free. Replace SLES with SCI/Decyl Glucoside blend while maintaining foam volume ≥200 mL and viscosity. Target the growing "clean beauty" consumer segment.',
    baseSKU: 'CW-DM-12',
    inputs: [
      { name: 'Sodium Cocoyl Isethionate %', type: 'ingredient_percentage', range: { min: 5, max: 15 }, unit: '%' },
      { name: 'Decyl Glucoside %', type: 'ingredient_percentage', range: { min: 2, max: 8 }, unit: '%' },
      { name: 'Cocamidopropyl Betaine %', type: 'ingredient_percentage', range: { min: 3, max: 8 }, unit: '%' },
      { name: 'Carbomer %', type: 'ingredient_percentage', range: { min: 0.1, max: 0.5 }, unit: '%' },
      { name: 'Guar HPC %', type: 'ingredient_percentage', range: { min: 0.1, max: 0.5 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 200, max: 500 }, unit: 'RPM' },
      { name: 'Temperature', type: 'processing_condition', range: { min: 35, max: 55 }, unit: '°C' },
    ],
    outcomes: [
      { name: 'Foam Volume', unit: 'mL', direction: 'maximize', importance: 'primary' },
      { name: 'Viscosity', unit: 'cP', direction: 'target', targetValue: 7000, importance: 'primary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'secondary' },
      { name: 'Wet Combing Force Reduction', unit: '%', direction: 'maximize', importance: 'secondary' },
      { name: 'Flash Lather Score', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Shelf Stability', unit: 'months', direction: 'maximize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Maintain foam volume ≥ 200 mL', metric: 'Foam Volume', goal: 'maximize', targetValue: 200, priority: 1 },
      { description: 'Achieve viscosity 5000-9000 cP without salt thickening', metric: 'Viscosity', goal: 'target', targetValue: 7000, priority: 2 },
      { description: 'Keep COGS within 20% of original ($0.38 → max $0.46)', metric: 'COGS per unit', goal: 'minimize', targetValue: 0.46, priority: 3 },
    ],
    constraints: [
      { description: 'No SLES or SLS (0%)', type: 'ingredient_limit', parameter: 'SLES', operator: '==', value: 0, unit: '%' },
      { description: 'Foam volume ≥ 170 mL minimum', type: 'regulatory', parameter: 'Foam Volume', operator: '>=', value: 170, unit: 'mL' },
      { description: 'pH between 4.5 and 6.0', type: 'regulatory', parameter: 'pH', operator: 'between', value: [4.5, 6.0] },
      { description: 'COGS ≤ $0.55/unit', type: 'cost_limit', parameter: 'COGS', operator: '<=', value: 0.55, unit: '$' },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },
  {
    name: 'Anti-Dandruff Efficacy Boost',
    type: 'performance_optimization',
    description:
      'Improve dandruff reduction efficacy of CW-AD-12 from 75% to ≥85% while reducing scalp irritation. Explore ZPT concentration optimization and synergy with tea tree oil and niacinamide.',
    baseSKU: 'CW-AD-12',
    inputs: [
      { name: 'Zinc Pyrithione %', type: 'ingredient_percentage', range: { min: 0.5, max: 2 }, unit: '%' },
      { name: 'Tea Tree Oil %', type: 'ingredient_percentage', range: { min: 0, max: 1 }, unit: '%' },
      { name: 'Niacinamide %', type: 'ingredient_percentage', range: { min: 0.5, max: 2 }, unit: '%' },
      { name: 'Salicylic Acid %', type: 'ingredient_percentage', range: { min: 0, max: 2 }, unit: '%' },
      { name: 'Menthol %', type: 'ingredient_percentage', range: { min: 0, max: 0.5 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 300, max: 600 }, unit: 'RPM' },
    ],
    outcomes: [
      // ── Primary: efficacy & safety ──
      { name: 'Dandruff Reduction', unit: '%', direction: 'maximize', importance: 'primary' },
      { name: 'Scalp Irritation Score', unit: '/10', direction: 'minimize', importance: 'primary' },
      // ── Secondary: lather & rinse performance ──
      { name: 'Foam Volume', unit: 'mL', direction: 'target', targetValue: 250, importance: 'secondary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'secondary' },
      // ── Lather properties (2nd wash) ──
      { name: 'Lather Amount (2nd Wash)', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'Foam Resistance', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Lather Creaminess', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── 2nd Rinsing ──
      { name: 'Rinse Time', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Alignment During Rinse', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Slippery Feel After Rinse', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── Wet stage ──
      { name: 'Wet Combing Ease', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Wet Slippery Feel', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Wet Product Coating', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── Dry stage ──
      { name: 'Dry Combing Ease', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Volume / Fullness', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Fluffy Hair', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Dry Slippery Feel', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Surface Smoothness', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Dry Product Coating', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Elasticity', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Dryness', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Tip Dryness', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Weight', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Shine', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Style Retention', unit: '/10', direction: 'maximize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Achieve dandruff reduction ≥ 85%', metric: 'Dandruff Reduction', goal: 'maximize', targetValue: 85, priority: 1 },
      { description: 'Keep scalp irritation ≤ 2.5', metric: 'Scalp Irritation Score', goal: 'minimize', targetValue: 2.5, priority: 2 },
      { description: 'Maintain sensory score ≥ 7.5', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 7.5, priority: 3 },
    ],
    constraints: [
      { description: 'ZPT ≤ 2% (FDA OTC limit)', type: 'regulatory', parameter: 'Zinc Pyrithione', operator: '<=', value: 2, unit: '%' },
      { description: 'Total active load ≤ 5%', type: 'ingredient_limit', parameter: 'total_actives', operator: '<=', value: 5, unit: '%' },
      { description: 'pH between 5.0 and 5.8', type: 'regulatory', parameter: 'pH', operator: 'between', value: [5.0, 5.8] },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },
  {
    name: 'Anti-Dandruff Sensory Deep Dive',
    type: 'performance_optimization',
    description:
      'Extended sensory evaluation of CleanWave Anti-Dandruff (CW-AD-12) covering lather properties (2nd wash), rinsing behavior, wet stage conditioning, and dry stage attributes. Full 26-outcome panel to characterize formulation performance across all consumer-perceptible dimensions.',
    baseSKU: 'CW-AD-12',
    inputs: [
      { name: 'Zinc Pyrithione %', type: 'ingredient_percentage', range: { min: 0.5, max: 2 }, unit: '%' },
      { name: 'Tea Tree Oil %', type: 'ingredient_percentage', range: { min: 0, max: 1 }, unit: '%' },
      { name: 'Niacinamide %', type: 'ingredient_percentage', range: { min: 0.5, max: 2 }, unit: '%' },
      { name: 'Salicylic Acid %', type: 'ingredient_percentage', range: { min: 0, max: 2 }, unit: '%' },
      { name: 'Menthol %', type: 'ingredient_percentage', range: { min: 0, max: 0.5 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 300, max: 600 }, unit: 'RPM' },
    ],
    outcomes: [
      // ── Primary: efficacy & safety ──
      { name: 'Dandruff Reduction', unit: '%', direction: 'maximize', importance: 'primary' },
      { name: 'Scalp Irritation Score', unit: '/10', direction: 'minimize', importance: 'primary' },
      // ── Secondary: lather & rinse performance ──
      { name: 'Foam Volume', unit: 'mL', direction: 'target', targetValue: 250, importance: 'secondary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'secondary' },
      // ── Lather properties (2nd wash) ──
      { name: 'Lather Amount (2nd Wash)', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'Foam Resistance', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Lather Creaminess', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── 2nd Rinsing ──
      { name: 'Rinse Time', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Alignment During Rinse', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Slippery Feel After Rinse', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── Wet stage ──
      { name: 'Wet Combing Ease', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Wet Slippery Feel', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Wet Product Coating', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      // ── Dry stage ──
      { name: 'Dry Combing Ease', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Volume / Fullness', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Fluffy Hair', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Dry Slippery Feel', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Surface Smoothness', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Dry Product Coating', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Elasticity', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Hair Dryness', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Tip Dryness', unit: '/10', direction: 'minimize', importance: 'tertiary' },
      { name: 'Hair Weight', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Shine', unit: '/10', direction: 'maximize', importance: 'tertiary' },
      { name: 'Style Retention', unit: '/10', direction: 'maximize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Achieve dandruff reduction ≥ 85%', metric: 'Dandruff Reduction', goal: 'maximize', targetValue: 85, priority: 1 },
      { description: 'Keep scalp irritation ≤ 2.5', metric: 'Scalp Irritation Score', goal: 'minimize', targetValue: 2.5, priority: 2 },
      { description: 'Maintain sensory score ≥ 7.5', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 7.5, priority: 3 },
    ],
    constraints: [
      { description: 'ZPT ≤ 2% (FDA OTC limit)', type: 'regulatory', parameter: 'Zinc Pyrithione', operator: '<=', value: 2, unit: '%' },
      { description: 'Total active load ≤ 5%', type: 'ingredient_limit', parameter: 'total_actives', operator: '<=', value: 5, unit: '%' },
      { description: 'pH between 5.0 and 5.8', type: 'regulatory', parameter: 'pH', operator: 'between', value: [5.0, 5.8] },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },
  {
    name: 'Clean Beauty Gen-Z Shampoo',
    type: 'new_audience',
    description:
      'Develop a new shampoo targeting Gen-Z consumers (18-25) with "clean beauty" positioning: sulfate-free, silicone-free, paraben-free, with natural/plant-derived hero ingredients. Must be Instagram-worthy (clear gel or pastel) with strong scent differentiation.',
    inputs: [
      { name: 'Sodium Cocoyl Isethionate %', type: 'ingredient_percentage', range: { min: 5, max: 12 }, unit: '%' },
      { name: 'Decyl Glucoside %', type: 'ingredient_percentage', range: { min: 3, max: 8 }, unit: '%' },
      { name: 'Aloe Vera Juice %', type: 'ingredient_percentage', range: { min: 1, max: 5 }, unit: '%' },
      { name: 'Coconut Oil %', type: 'ingredient_percentage', range: { min: 0.5, max: 3 }, unit: '%' },
      { name: 'Caffeine %', type: 'ingredient_percentage', range: { min: 0, max: 0.5 }, unit: '%' },
      { name: 'Biotin %', type: 'ingredient_percentage', range: { min: 0, max: 0.1 }, unit: '%' },
      { name: 'Temperature', type: 'processing_condition', range: { min: 35, max: 50 }, unit: '°C' },
    ],
    outcomes: [
      { name: 'Foam Volume', unit: 'mL', direction: 'maximize', importance: 'primary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'primary' },
      { name: 'Natural Origin Index', unit: '%', direction: 'maximize', importance: 'secondary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'secondary' },
      { name: 'Shelf Stability', unit: 'months', direction: 'maximize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Achieve foam volume ≥ 180 mL', metric: 'Foam Volume', goal: 'maximize', targetValue: 180, priority: 1 },
      { description: 'Sensory score ≥ 8.5', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 8.5, priority: 2 },
      { description: 'Natural origin ≥ 90%', metric: 'Natural Origin Index', goal: 'maximize', targetValue: 90, priority: 3 },
      { description: 'COGS ≤ $0.80/unit', metric: 'COGS per unit', goal: 'minimize', targetValue: 0.80, priority: 4 },
    ],
    constraints: [
      { description: 'No sulfates (SLES, SLS = 0%)', type: 'ingredient_limit', parameter: 'sulfates', operator: '==', value: 0, unit: '%' },
      { description: 'No silicones (Dimethicone = 0%)', type: 'ingredient_limit', parameter: 'silicones', operator: '==', value: 0, unit: '%' },
      { description: 'pH between 4.5 and 5.5', type: 'regulatory', parameter: 'pH', operator: 'between', value: [4.5, 5.5] },
      { description: 'COGS ≤ $1.00/unit', type: 'cost_limit', parameter: 'COGS', operator: '<=', value: 1.00, unit: '$' },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },
];

export const SHAMPOO_CONFIG: CategoryConfig = {
  name: 'Shampoo',
  ingredients: SHAMPOO_INGREDIENTS,
  skus: SHAMPOO_SKUS,
  projects: SHAMPOO_PROJECTS,
};
