import type {
  Ingredient,
  SKU,
  InnovationProject,
  CategoryConfig,
} from '../types.js';

// ============================================================
// TOOTHPASTE INGREDIENT LIBRARY — 48 ingredients
// ============================================================

const TOOTHPASTE_INGREDIENTS: Ingredient[] = [
  // ── Abrasives (1-5) ──────────────────────────────────────
  {
    name: 'Hydrated Silica',
    inci: 'Hydrated Silica',
    category: 'Abrasive',
    supplier: 'Evonik',
    costPerKg: 4,
    properties: { usageMin: 15, usageMax: 25, rdaContribution: 'moderate' },
    description: 'Primary abrasive in most modern pastes.',
  },
  {
    name: 'Calcium Carbonate',
    inci: 'Calcium Carbonate',
    category: 'Abrasive',
    supplier: 'Omya',
    costPerKg: 1,
    properties: { usageMin: 20, usageMax: 40, rdaContribution: 'moderate-high' },
    description: 'Traditional abrasive, cost-effective.',
  },
  {
    name: 'Dicalcium Phosphate Dihydrate',
    inci: 'Dicalcium Phosphate Dihydrate',
    category: 'Abrasive',
    supplier: 'Innophos',
    costPerKg: 2,
    properties: { usageMin: 15, usageMax: 30 },
    description: 'Gentle abrasive, good compatibility.',
  },
  {
    name: 'Alumina',
    tradeName: 'Aluminum Oxide',
    inci: 'Alumina',
    category: 'Abrasive',
    supplier: 'Saint-Gobain',
    costPerKg: 5,
    properties: { usageMin: 5, usageMax: 15, cleaningEfficacy: 'high' },
    description: 'Premium abrasive for whitening.',
  },
  {
    name: 'Perlite',
    inci: 'Perlite',
    category: 'Abrasive',
    supplier: 'Imerys',
    costPerKg: 2,
    properties: { usageMin: 5, usageMax: 10 },
    description: 'Natural volcanic glass, eco-friendly positioning.',
  },

  // ── Fluoride Sources (6-8) ───────────────────────────────
  {
    name: 'Sodium Fluoride',
    tradeName: 'Kohinoor NaF',
    inci: 'Sodium Fluoride',
    category: 'Fluoride Source',
    supplier: 'Solvay',
    costPerKg: 8,
    properties: { usageMin: 0.22, usageMax: 0.32, fluoridePpmRange: '1000-1100' },
    regulatoryNotes: 'Max 0.32% w/w as NaF per FDA',
    description: 'Standard fluoride source.',
  },
  {
    name: 'Sodium Monofluorophosphate',
    tradeName: 'MFP',
    inci: 'Sodium Monofluorophosphate',
    category: 'Fluoride Source',
    supplier: 'Mexichem',
    costPerKg: 12,
    properties: { usageMin: 0.70, usageMax: 0.76 },
    regulatoryNotes: 'Max 0.76% per FDA. Compatible with calcium abrasives.',
    description: 'Compatible with calcium abrasives.',
  },
  {
    name: 'Stannous Fluoride',
    inci: 'Stannous Fluoride',
    category: 'Fluoride Source',
    supplier: 'Novaflux',
    costPerKg: 55,
    properties: { usageMin: 0.454, usageMax: 0.454 },
    regulatoryNotes: 'Anti-gingivitis + anti-sensitivity + anti-cavity',
    description: 'Premium ingredient. Used at 0.454%.',
  },

  // ── Surfactants (9-11) ───────────────────────────────────
  {
    name: 'Sodium Lauryl Sulfate',
    tradeName: 'SLS',
    inci: 'Sodium Lauryl Sulfate',
    category: 'Surfactant',
    supplier: 'BASF',
    costPerKg: 2,
    properties: { usageMin: 1, usageMax: 2 },
    regulatoryNotes: 'Can cause irritation in sensitive individuals.',
    description: 'Standard foaming agent.',
  },
  {
    name: 'Cocamidopropyl Betaine',
    inci: 'Cocamidopropyl Betaine',
    category: 'Surfactant',
    supplier: 'Colonial Chemical',
    costPerKg: 5,
    properties: { usageMin: 1, usageMax: 3 },
    description: 'Mild surfactant, SLS-free formulations.',
  },
  {
    name: 'Sodium Methyl Cocoyl Taurate',
    inci: 'Sodium Methyl Cocoyl Taurate',
    category: 'Surfactant',
    supplier: 'Innospec',
    costPerKg: 8,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Ultra-mild, premium.',
  },

  // ── Humectants (12-15) ───────────────────────────────────
  {
    name: 'Glycerin',
    inci: 'Glycerin',
    category: 'Humectant',
    supplier: 'P&G Chemicals',
    costPerKg: 1,
    properties: { usageMin: 20, usageMax: 40 },
    description: 'Primary humectant, prevents drying.',
  },
  {
    name: 'Sorbitol',
    tradeName: 'Sorbitol 70% Solution',
    inci: 'Sorbitol',
    category: 'Humectant',
    supplier: 'Roquette',
    costPerKg: 1,
    properties: { usageMin: 20, usageMax: 40 },
    description: 'Humectant + sweetener.',
  },
  {
    name: 'Propylene Glycol',
    inci: 'Propylene Glycol',
    category: 'Humectant',
    supplier: 'Dow Chemical',
    costPerKg: 2,
    properties: { usageMin: 3, usageMax: 10 },
    description: 'Humectant, solvent.',
  },
  {
    name: 'PEG-8',
    inci: 'PEG-8',
    category: 'Humectant',
    supplier: 'Dow Chemical',
    costPerKg: 3,
    properties: { usageMin: 3, usageMax: 8 },
    description: 'Humectant for smooth texture.',
  },

  // ── Binders / Thickeners (16-20) ────────────────────────
  {
    name: 'Carboxymethyl Cellulose',
    tradeName: 'CMC',
    inci: 'Cellulose Gum',
    category: 'Binder / Thickener',
    supplier: 'Ashland',
    costPerKg: 4,
    properties: { usageMin: 0.5, usageMax: 1.5 },
    description: 'Standard binder.',
  },
  {
    name: 'Xanthan Gum',
    inci: 'Xanthan Gum',
    category: 'Binder / Thickener',
    supplier: 'CP Kelco',
    costPerKg: 4,
    properties: { usageMin: 0.3, usageMax: 1.0, rheology: 'shear-thinning' },
    description: 'Natural thickener, shear-thinning.',
  },
  {
    name: 'Carbomer 956',
    inci: 'Carbomer',
    category: 'Binder / Thickener',
    supplier: 'Lubrizol',
    costPerKg: 18,
    properties: { usageMin: 0.2, usageMax: 0.8, clarity: 'excellent' },
    description: 'Synthetic thickener, excellent clarity.',
  },
  {
    name: 'Hydroxyethyl Cellulose',
    inci: 'Hydroxyethyl Cellulose',
    category: 'Binder / Thickener',
    supplier: 'Ashland',
    costPerKg: 6,
    properties: { usageMin: 0.5, usageMax: 1.5 },
    description: 'Mild thickener.',
  },
  {
    name: 'Cellulose Gum',
    inci: 'Cellulose Gum',
    category: 'Binder / Thickener',
    supplier: 'Nouryon',
    costPerKg: 5,
    properties: { usageMin: 0.5, usageMax: 1.0 },
    description: 'Natural origin binder.',
  },

  // ── Flavors / Sweeteners (21-26) ────────────────────────
  {
    name: 'Peppermint Oil',
    inci: 'Mentha Piperita Oil',
    category: 'Flavor / Sweetener',
    supplier: 'Givaudan',
    costPerKg: 25,
    properties: { usageMin: 0.8, usageMax: 1.5 },
    description: 'Classic mint flavor.',
  },
  {
    name: 'Spearmint Oil',
    inci: 'Mentha Viridis Oil',
    category: 'Flavor / Sweetener',
    supplier: 'Firmenich',
    costPerKg: 20,
    properties: { usageMin: 0.8, usageMax: 1.5 },
    description: 'Milder mint flavor.',
  },
  {
    name: 'Bubblegum Flavor',
    tradeName: 'Bubblegum Flavor (artificial)',
    inci: 'Flavor',
    category: 'Flavor / Sweetener',
    supplier: 'IFF',
    costPerKg: 15,
    properties: { usageMin: 0.5, usageMax: 1.0 },
    description: 'For kids products.',
  },
  {
    name: 'Sodium Saccharin',
    inci: 'Sodium Saccharin',
    category: 'Flavor / Sweetener',
    supplier: 'PMC Specialties',
    costPerKg: 10,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Artificial sweetener.',
  },
  {
    name: 'Stevia Extract',
    inci: 'Stevia Rebaudiana Leaf Extract',
    category: 'Flavor / Sweetener',
    supplier: 'PureCircle',
    costPerKg: 35,
    properties: { usageMin: 0.05, usageMax: 0.2 },
    description: 'Natural sweetener.',
  },
  {
    name: 'Cinnamint Flavor',
    inci: 'Flavor',
    category: 'Flavor / Sweetener',
    supplier: 'Symrise',
    costPerKg: 22,
    properties: { usageMin: 0.8, usageMax: 1.2 },
    description: 'Specialty flavor.',
  },

  // ── Preservatives (27-29) ───────────────────────────────
  {
    name: 'Sodium Benzoate',
    inci: 'Sodium Benzoate',
    category: 'Preservative',
    supplier: 'Emerald Kalama',
    costPerKg: 4,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Preservative.',
  },
  {
    name: 'Methylparaben',
    inci: 'Methylparaben',
    category: 'Preservative',
    supplier: 'Sharon Laboratories',
    costPerKg: 12,
    properties: { usageMin: 0.1, usageMax: 0.2 },
    description: 'Traditional preservative.',
  },
  {
    name: 'Phenoxyethanol',
    inci: 'Phenoxyethanol',
    category: 'Preservative',
    supplier: 'Schülke',
    costPerKg: 8,
    properties: { usageMin: 0.5, usageMax: 1.0 },
    description: 'Paraben-free preservative.',
  },

  // ── Active / Specialty Ingredients (30-40) ──────────────
  {
    name: 'Potassium Nitrate',
    inci: 'Potassium Nitrate',
    category: 'Sensitivity Agent',
    supplier: 'SQM',
    costPerKg: 6,
    properties: { usageMin: 5, usageMax: 5 },
    regulatoryNotes: '5% required for sensitivity relief claim.',
    description: 'Sensitivity relief active.',
  },
  {
    name: 'Strontium Chloride',
    inci: 'Strontium Chloride',
    category: 'Sensitivity Agent',
    supplier: 'Solvay',
    costPerKg: 8,
    properties: { usageMin: 10, usageMax: 10 },
    description: 'Sensitivity, older technology.',
  },
  {
    name: 'Triclosan',
    inci: 'Triclosan',
    category: 'Active Ingredient',
    supplier: 'BASF',
    costPerKg: 15,
    properties: { usageMin: 0.2, usageMax: 0.3 },
    regulatoryNotes: 'Being phased out in some markets.',
    description: 'Antibacterial.',
  },
  {
    name: 'Zinc Citrate',
    inci: 'Zinc Citrate',
    category: 'Active Ingredient',
    supplier: 'Jungbunzlauer',
    costPerKg: 10,
    properties: { usageMin: 0.5, usageMax: 2.0 },
    description: 'Anti-tartar, fresh breath.',
  },
  {
    name: 'Hydrogen Peroxide',
    inci: 'Hydrogen Peroxide',
    category: 'Whitening Agent',
    supplier: 'Evonik',
    costPerKg: 3,
    properties: { usageMin: 1, usageMax: 3 },
    description: 'Whitening active.',
  },
  {
    name: 'Activated Charcoal',
    inci: 'Charcoal Powder',
    category: 'Whitening Agent',
    supplier: 'Jacobi Carbons',
    costPerKg: 2,
    properties: { usageMin: 1, usageMax: 3 },
    description: 'Trendy whitening ingredient.',
  },
  {
    name: 'Hydroxyapatite',
    tradeName: 'Nano Hydroxyapatite',
    inci: 'Hydroxyapatite',
    category: 'Active Ingredient',
    supplier: 'Sangi Co.',
    costPerKg: 45,
    properties: { usageMin: 5, usageMax: 10 },
    regulatoryNotes: 'Fluoride alternative in some markets.',
    description: 'Remineralization active.',
  },
  {
    name: 'Aloe Vera Extract',
    inci: 'Aloe Barbadensis Leaf Juice',
    category: 'Natural Extract',
    supplier: 'Terry Laboratories',
    costPerKg: 15,
    properties: { usageMin: 0.5, usageMax: 2 },
    description: 'Soothing, natural positioning.',
  },
  {
    name: 'Tea Tree Oil',
    inci: 'Melaleuca Alternifolia Leaf Oil',
    category: 'Natural Extract',
    supplier: 'Australian Botanical Products',
    costPerKg: 30,
    properties: { usageMin: 0.3, usageMax: 1 },
    description: 'Natural antibacterial.',
  },
  {
    name: 'Coenzyme Q10',
    inci: 'Ubiquinone',
    category: 'Active Ingredient',
    supplier: 'Kaneka',
    costPerKg: 200,
    properties: { usageMin: 0.01, usageMax: 0.05 },
    description: 'Gum health (premium).',
  },
  {
    name: 'Baking Soda',
    tradeName: 'Sodium Bicarbonate',
    inci: 'Sodium Bicarbonate',
    category: 'Abrasive',
    supplier: 'Church & Dwight',
    costPerKg: 1,
    properties: { usageMin: 20, usageMax: 50 },
    description: 'Whitening, freshness.',
  },

  // ── Colorants (41-44) ───────────────────────────────────
  {
    name: 'Titanium Dioxide',
    inci: 'CI 77891',
    category: 'Colorant',
    supplier: 'Chemours',
    costPerKg: 5,
    properties: { usageMin: 0.25, usageMax: 1.0 },
    description: 'White opacity.',
  },
  {
    name: 'FD&C Blue No. 1',
    inci: 'CI 42090',
    category: 'Colorant',
    supplier: 'Sensient',
    costPerKg: 40,
    properties: { usageMin: 0.001, usageMax: 0.01 },
    description: 'Blue colorant.',
  },
  {
    name: 'FD&C Red No. 40',
    inci: 'CI 16035',
    category: 'Colorant',
    supplier: 'Sensient',
    costPerKg: 35,
    properties: { usageMin: 0.001, usageMax: 0.01 },
    description: 'Red colorant.',
  },
  {
    name: 'Mica',
    tradeName: 'Mica (natural)',
    inci: 'CI 77019',
    category: 'Colorant',
    supplier: 'Sun Chemical',
    costPerKg: 12,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'Shimmer effect.',
  },

  // ── pH Adjusters / Solvents (45-48) ─────────────────────
  {
    name: 'Sodium Hydroxide',
    inci: 'Sodium Hydroxide',
    category: 'pH Adjuster',
    supplier: 'Olin Corporation',
    costPerKg: 1,
    properties: { usageMin: 0.1, usageMax: 0.5 },
    description: 'pH adjuster.',
  },
  {
    name: 'Citric Acid',
    inci: 'Citric Acid',
    category: 'pH Adjuster',
    supplier: 'ADM',
    costPerKg: 2,
    properties: { usageMin: 0.1, usageMax: 0.3 },
    description: 'pH adjuster, natural.',
  },
  {
    name: 'Water',
    tradeName: 'Aqua',
    inci: 'Aqua',
    category: 'Solvent',
    supplier: 'N/A',
    costPerKg: 1,
    properties: { usageMin: 15, usageMax: 35 },
    description: 'Solvent/base.',
  },
  {
    name: 'Tetrasodium Pyrophosphate',
    inci: 'Tetrasodium Pyrophosphate',
    category: 'Active Ingredient',
    supplier: 'ICL',
    costPerKg: 4,
    properties: { usageMin: 1, usageMax: 3 },
    description: 'Anti-tartar.',
  },
];

// ============================================================
// TOOTHPASTE SKU LIBRARY — 10 formulations
// All percentageW values sum to exactly 100%
// ============================================================

const TOOTHPASTE_SKUS: SKU[] = [
  // SKU 1: FreshSmile Classic Clean 6.0oz
  {
    name: 'FreshSmile Classic Clean 6.0oz',
    code: 'FS-CC-60',
    targetDemographic: 'General adult, mass market',
    targetGeo: 'North America',
    positioningStatement: 'Reliable everyday cavity protection',
    formulation: [
      { ingredientName: 'Water', percentageW: 28, role: 'Solvent' },
      { ingredientName: 'Sorbitol', percentageW: 22, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 18, role: 'Abrasive' },
      { ingredientName: 'Glycerin', percentageW: 12, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 7.495, role: 'Humectant' },
      { ingredientName: 'PEG-8', percentageW: 5.0, role: 'Humectant' },
      { ingredientName: 'Tetrasodium Pyrophosphate', percentageW: 2.0, role: 'Anti-tartar' },
      { ingredientName: 'Sodium Lauryl Sulfate', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Carboxymethyl Cellulose', percentageW: 1.0, role: 'Binder' },
      { ingredientName: 'Peppermint Oil', percentageW: 1.0, role: 'Flavor' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.5, role: 'Opacifier' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.3, role: 'Sweetener' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.24, role: 'Fluoride source' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.16, role: 'pH adjuster' },
      { ingredientName: 'FD&C Blue No. 1', percentageW: 0.005, role: 'Colorant' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 800, unit: 'RPM', range: { min: 600, max: 1000 } },
      { name: 'Temperature', value: 25, unit: '°C', range: { min: 20, max: 30 } },
      { name: 'Mixing Time', value: 45, unit: 'minutes', range: { min: 30, max: 60 } },
      { name: 'Vacuum', value: -0.5, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 850, unit: 'ppm', target: { min: 800, ideal: 900 }, higherIsBetter: true },
      { name: 'RDA', value: 75, unit: '', target: { max: 150, ideal: 70 } },
      { name: 'Viscosity', value: 85000, unit: 'cP', target: { min: 70000, max: 100000, ideal: 85000 } },
      { name: 'pH', value: 7.0, unit: '', target: { min: 6.5, max: 7.5, ideal: 7.0 } },
      { name: 'Overall Sensory Score', value: 7.2, unit: '/10', target: { min: 6.5, ideal: 8.0 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.42,
    retailPrice: 3.99,
  },

  // SKU 2: FreshSmile Kids Bubblegum 4.2oz
  {
    name: 'FreshSmile Kids Bubblegum 4.2oz',
    code: 'FS-KIDS-BG-42',
    targetDemographic: 'Children 3-12',
    targetGeo: 'North America',
    positioningStatement: 'Fun cavity-fighting paste kids actually love',
    formulation: [
      { ingredientName: 'Water', percentageW: 30, role: 'Solvent' },
      { ingredientName: 'Sorbitol', percentageW: 25, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 15, role: 'Abrasive' },
      { ingredientName: 'Glycerin', percentageW: 14, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 6.885, role: 'Humectant' },
      { ingredientName: 'PEG-8', percentageW: 4.0, role: 'Humectant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Bubblegum Flavor', percentageW: 0.8, role: 'Flavor' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.8, role: 'Thickener' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.6, role: 'Preservative' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.4, role: 'Sweetener' },
      { ingredientName: 'Mica', percentageW: 0.3, role: 'Shimmer' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.11, role: 'Fluoride source (500 ppm F for kids)' },
      { ingredientName: 'Citric Acid', percentageW: 0.1, role: 'pH adjuster' },
      { ingredientName: 'FD&C Red No. 40', percentageW: 0.005, role: 'Colorant' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 600, unit: 'RPM', range: { min: 400, max: 800 } },
      { name: 'Temperature', value: 22, unit: '°C', range: { min: 18, max: 26 } },
      { name: 'Mixing Time', value: 40, unit: 'minutes', range: { min: 30, max: 50 } },
      { name: 'Vacuum', value: -0.5, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 420, unit: 'ppm', target: { min: 400, ideal: 500 }, higherIsBetter: true },
      { name: 'RDA', value: 50, unit: '', target: { max: 70, ideal: 50 } },
      { name: 'Viscosity', value: 65000, unit: 'cP', target: { min: 50000, max: 80000, ideal: 65000 } },
      { name: 'pH', value: 6.8, unit: '', target: { min: 6.5, max: 7.5 } },
      { name: 'Overall Sensory Score', value: 8.5, unit: '/10', target: { min: 7.0, ideal: 9.0 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 18, unit: 'months', target: { min: 12 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.55,
    retailPrice: 4.49,
  },

  // SKU 3: FreshSmile Sensitive Pro 4.0oz
  {
    name: 'FreshSmile Sensitive Pro 4.0oz',
    code: 'FS-SENS-40',
    targetDemographic: 'Adults with sensitivity, 25-65',
    targetGeo: 'North America, Europe',
    positioningStatement: 'Clinically proven sensitivity relief',
    formulation: [
      { ingredientName: 'Glycerin', percentageW: 25, role: 'Humectant' },
      { ingredientName: 'Water', percentageW: 25, role: 'Solvent' },
      { ingredientName: 'Sorbitol', percentageW: 15, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 12, role: 'Abrasive' },
      { ingredientName: 'Propylene Glycol', percentageW: 7.75, role: 'Humectant' },
      { ingredientName: 'Potassium Nitrate', percentageW: 5.0, role: 'Desensitizer' },
      { ingredientName: 'PEG-8', percentageW: 5.0, role: 'Humectant' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 1.2, role: 'Surfactant' },
      { ingredientName: 'Spearmint Oil', percentageW: 1.0, role: 'Flavor' },
      { ingredientName: 'Carboxymethyl Cellulose', percentageW: 0.8, role: 'Binder' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.6, role: 'Thickener' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.5, role: 'Preservative' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.5, role: 'Opacifier' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.25, role: 'Fluoride source' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.2, role: 'pH adjuster' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.2, role: 'Sweetener' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 500, unit: 'RPM', range: { min: 400, max: 700 } },
      { name: 'Temperature', value: 23, unit: '°C', range: { min: 20, max: 28 } },
      { name: 'Mixing Time', value: 50, unit: 'minutes', range: { min: 40, max: 60 } },
      { name: 'Vacuum', value: -0.6, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 920, unit: 'ppm', target: { min: 850, ideal: 950 }, higherIsBetter: true },
      { name: 'RDA', value: 60, unit: '', target: { max: 80, ideal: 60 } },
      { name: 'Viscosity', value: 95000, unit: 'cP', target: { min: 80000, max: 110000 } },
      { name: 'pH', value: 7.2, unit: '', target: { min: 6.8, max: 7.5 } },
      { name: 'Overall Sensory Score', value: 7.8, unit: '/10', target: { min: 7.0 }, higherIsBetter: true },
      { name: 'Dentin Tubule Occlusion', value: 78, unit: '%', target: { min: 70 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.68,
    retailPrice: 6.99,
  },

  // SKU 4: FreshSmile Brilliant White 3.5oz
  {
    name: 'FreshSmile Brilliant White 3.5oz',
    code: 'FS-BW-35',
    targetDemographic: 'Young adults 18-35, cosmetic-conscious',
    targetGeo: 'North America',
    positioningStatement: 'Visibly whiter teeth in 2 weeks',
    formulation: [
      { ingredientName: 'Water', percentageW: 22, role: 'Solvent' },
      { ingredientName: 'Hydrated Silica', percentageW: 20, role: 'Abrasive' },
      { ingredientName: 'Glycerin', percentageW: 20, role: 'Humectant' },
      { ingredientName: 'Sorbitol', percentageW: 12, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 6.76, role: 'Humectant' },
      { ingredientName: 'Alumina', percentageW: 5.0, role: 'Whitening abrasive' },
      { ingredientName: 'PEG-8', percentageW: 5.0, role: 'Humectant' },
      { ingredientName: 'Hydrogen Peroxide', percentageW: 2.0, role: 'Whitening active' },
      { ingredientName: 'Tetrasodium Pyrophosphate', percentageW: 2.0, role: 'Anti-tartar' },
      { ingredientName: 'Sodium Lauryl Sulfate', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Peppermint Oil', percentageW: 1.2, role: 'Flavor' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.8, role: 'Opacifier' },
      { ingredientName: 'Carbomer 956', percentageW: 0.5, role: 'Thickener' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.4, role: 'pH adjuster' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.3, role: 'Sweetener' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.24, role: 'Fluoride source' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 700, unit: 'RPM', range: { min: 500, max: 900 } },
      { name: 'Temperature', value: 20, unit: '°C', range: { min: 18, max: 25 } },
      { name: 'Mixing Time', value: 35, unit: 'minutes', range: { min: 25, max: 50 } },
      { name: 'Vacuum', value: -0.7, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 880, unit: 'ppm', target: { min: 850, ideal: 900 }, higherIsBetter: true },
      { name: 'RDA', value: 120, unit: '', target: { max: 150, ideal: 100 } },
      { name: 'Viscosity', value: 78000, unit: 'cP', target: { min: 65000, max: 90000 } },
      { name: 'pH', value: 6.5, unit: '', target: { min: 5.5, max: 7.0 } },
      { name: 'Overall Sensory Score', value: 7.5, unit: '/10', target: { min: 7.0 }, higherIsBetter: true },
      { name: 'Whitening Shade Change', value: 2.1, unit: 'delta-E', target: { min: 1.5 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 18, unit: 'months', target: { min: 12 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.82,
    retailPrice: 7.99,
  },

  // SKU 5: FreshSmile Natural Botanicals 5.5oz
  {
    name: 'FreshSmile Natural Botanicals 5.5oz',
    code: 'FS-NAT-55',
    targetDemographic: 'Health-conscious adults 25-50',
    targetGeo: 'North America, Western Europe',
    positioningStatement: "Nature's way to a healthy smile",
    formulation: [
      { ingredientName: 'Water', percentageW: 30, role: 'Solvent' },
      { ingredientName: 'Glycerin', percentageW: 22, role: 'Humectant' },
      { ingredientName: 'Calcium Carbonate', percentageW: 20, role: 'Natural abrasive' },
      { ingredientName: 'Sorbitol', percentageW: 10, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 6.2, role: 'Humectant' },
      { ingredientName: 'Hydroxyapatite', percentageW: 5.0, role: 'Remineralization' },
      { ingredientName: 'Aloe Vera Extract', percentageW: 1.5, role: 'Soothing agent' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Peppermint Oil', percentageW: 1.0, role: 'Flavor' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.8, role: 'Thickener' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.6, role: 'Preservative' },
      { ingredientName: 'Tea Tree Oil', percentageW: 0.5, role: 'Antibacterial' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Citric Acid', percentageW: 0.2, role: 'pH adjuster' },
      { ingredientName: 'Stevia Extract', percentageW: 0.1, role: 'Natural sweetener' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.1, role: 'pH adjuster' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 600, unit: 'RPM', range: { min: 400, max: 800 } },
      { name: 'Temperature', value: 22, unit: '°C', range: { min: 18, max: 26 } },
      { name: 'Mixing Time', value: 55, unit: 'minutes', range: { min: 40, max: 65 } },
      { name: 'Vacuum', value: -0.5, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 0, unit: 'ppm' },
      { name: 'RDA', value: 65, unit: '', target: { max: 100, ideal: 65 } },
      { name: 'Viscosity', value: 82000, unit: 'cP', target: { min: 70000, max: 95000 } },
      { name: 'pH', value: 7.5, unit: '', target: { min: 7.0, max: 8.0 } },
      { name: 'Overall Sensory Score', value: 7.0, unit: '/10', target: { min: 6.5 }, higherIsBetter: true },
      { name: 'Remineralization Index', value: 72, unit: '%', target: { min: 60 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 18, unit: 'months', target: { min: 12 }, higherIsBetter: true },
    ],
    estimatedCOGS: 1.15,
    retailPrice: 9.99,
  },

  // SKU 6: FreshSmile Total Care 6.0oz
  {
    name: 'FreshSmile Total Care 6.0oz',
    code: 'FS-TC-60',
    targetDemographic: 'Adults 30-60, premium mass market',
    targetGeo: 'Global',
    positioningStatement: 'Complete protection for the whole family',
    formulation: [
      { ingredientName: 'Water', percentageW: 26, role: 'Solvent' },
      { ingredientName: 'Glycerin', percentageW: 20, role: 'Humectant' },
      { ingredientName: 'Sorbitol', percentageW: 18, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 16, role: 'Abrasive' },
      { ingredientName: 'Propylene Glycol', percentageW: 6.246, role: 'Humectant' },
      { ingredientName: 'PEG-8', percentageW: 5.0, role: 'Humectant' },
      { ingredientName: 'Zinc Citrate', percentageW: 1.5, role: 'Anti-tartar' },
      { ingredientName: 'Tetrasodium Pyrophosphate', percentageW: 1.5, role: 'Anti-tartar' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Carboxymethyl Cellulose', percentageW: 1.0, role: 'Binder' },
      { ingredientName: 'Spearmint Oil', percentageW: 1.0, role: 'Flavor' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.5, role: 'Opacifier' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Stannous Fluoride', percentageW: 0.454, role: 'Anti-cavity + anti-gingivitis' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.3, role: 'pH adjuster' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.2, role: 'Sweetener' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 700, unit: 'RPM', range: { min: 500, max: 900 } },
      { name: 'Temperature', value: 24, unit: '°C', range: { min: 20, max: 28 } },
      { name: 'Mixing Time', value: 50, unit: 'minutes', range: { min: 35, max: 60 } },
      { name: 'Vacuum', value: -0.6, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 1050, unit: 'ppm', target: { min: 950, ideal: 1100 }, higherIsBetter: true },
      { name: 'RDA', value: 80, unit: '', target: { max: 120, ideal: 80 } },
      { name: 'Viscosity', value: 90000, unit: 'cP', target: { min: 80000, max: 100000 } },
      { name: 'pH', value: 6.8, unit: '', target: { min: 6.5, max: 7.5 } },
      { name: 'Overall Sensory Score', value: 7.6, unit: '/10', target: { min: 7.0 }, higherIsBetter: true },
      { name: 'Anti-gingivitis Efficacy', value: 82, unit: '%', target: { min: 70 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.95,
    retailPrice: 5.99,
  },

  // SKU 7: FreshSmile Charcoal Detox 4.0oz
  {
    name: 'FreshSmile Charcoal Detox 4.0oz',
    code: 'FS-CHAR-40',
    targetDemographic: 'Millennials/Gen-Z 18-30',
    targetGeo: 'North America, Asia-Pacific',
    positioningStatement: 'Deep clean detox for a fresh start',
    formulation: [
      { ingredientName: 'Water', percentageW: 28, role: 'Solvent' },
      { ingredientName: 'Glycerin', percentageW: 22, role: 'Humectant' },
      { ingredientName: 'Sorbitol', percentageW: 15, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 14, role: 'Abrasive' },
      { ingredientName: 'Propylene Glycol', percentageW: 9.71, role: 'Humectant' },
      { ingredientName: 'PEG-8', percentageW: 4.0, role: 'Humectant' },
      { ingredientName: 'Activated Charcoal', percentageW: 2.5, role: 'Detox/whitening' },
      { ingredientName: 'Cocamidopropyl Betaine', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Cinnamint Flavor', percentageW: 1.0, role: 'Flavor' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.7, role: 'Thickener' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.5, role: 'Preservative' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.24, role: 'Fluoride source' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.2, role: 'Sweetener' },
      { ingredientName: 'Citric Acid', percentageW: 0.15, role: 'pH adjuster' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 800, unit: 'RPM', range: { min: 600, max: 1000 } },
      { name: 'Temperature', value: 23, unit: '°C', range: { min: 20, max: 28 } },
      { name: 'Mixing Time', value: 40, unit: 'minutes', range: { min: 30, max: 50 } },
      { name: 'Vacuum', value: -0.5, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 860, unit: 'ppm', target: { min: 800 }, higherIsBetter: true },
      { name: 'RDA', value: 95, unit: '', target: { max: 150, ideal: 90 } },
      { name: 'Viscosity', value: 72000, unit: 'cP', target: { min: 60000, max: 85000 } },
      { name: 'pH', value: 6.9, unit: '', target: { min: 6.5, max: 7.5 } },
      { name: 'Overall Sensory Score', value: 7.3, unit: '/10', target: { min: 6.5 }, higherIsBetter: true },
      { name: 'Stain Removal Index', value: 85, unit: '%', target: { min: 70 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 18, unit: 'months', target: { min: 12 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.72,
    retailPrice: 6.49,
  },

  // SKU 8: FreshSmile Value Protect 8.0oz
  {
    name: 'FreshSmile Value Protect 8.0oz',
    code: 'FS-VP-80',
    targetDemographic: 'Budget-conscious families',
    targetGeo: 'India, Southeast Asia, Latin America',
    positioningStatement: 'Trusted cavity protection for the whole family',
    formulation: [
      { ingredientName: 'Water', percentageW: 32, role: 'Solvent' },
      { ingredientName: 'Calcium Carbonate', percentageW: 25, role: 'Abrasive' },
      { ingredientName: 'Sorbitol', percentageW: 25, role: 'Humectant' },
      { ingredientName: 'Glycerin', percentageW: 8, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 4.44, role: 'Humectant' },
      { ingredientName: 'Sodium Lauryl Sulfate', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Carboxymethyl Cellulose', percentageW: 1.2, role: 'Binder' },
      { ingredientName: 'Sodium Monofluorophosphate', percentageW: 0.76, role: 'Fluoride source' },
      { ingredientName: 'Peppermint Oil', percentageW: 0.5, role: 'Flavor' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.4, role: 'Preservative' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.3, role: 'Sweetener' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.3, role: 'Opacifier' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.1, role: 'pH adjuster' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 900, unit: 'RPM', range: { min: 700, max: 1100 } },
      { name: 'Temperature', value: 25, unit: '°C', range: { min: 22, max: 30 } },
      { name: 'Mixing Time', value: 35, unit: 'minutes', range: { min: 25, max: 45 } },
      { name: 'Vacuum', value: -0.4, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 780, unit: 'ppm', target: { min: 700 }, higherIsBetter: true },
      { name: 'RDA', value: 90, unit: '', target: { max: 120, ideal: 85 } },
      { name: 'Viscosity', value: 70000, unit: 'cP', target: { min: 60000, max: 85000 } },
      { name: 'pH', value: 7.1, unit: '', target: { min: 6.5, max: 7.5 } },
      { name: 'Overall Sensory Score', value: 6.5, unit: '/10', target: { min: 6.0 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 30, unit: 'months', target: { min: 24 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.18,
    retailPrice: 1.49,
  },

  // SKU 9: FreshSmile Premium Repair 3.0oz
  {
    name: 'FreshSmile Premium Repair 3.0oz',
    code: 'FS-PR-30',
    targetDemographic: 'Affluent adults 35-65',
    targetGeo: 'Japan, South Korea, Western Europe',
    positioningStatement: 'Advanced enamel repair technology',
    formulation: [
      { ingredientName: 'Glycerin', percentageW: 25, role: 'Humectant' },
      { ingredientName: 'Water', percentageW: 22, role: 'Solvent' },
      { ingredientName: 'Propylene Glycol', percentageW: 12.82, role: 'Humectant' },
      { ingredientName: 'Sorbitol', percentageW: 12, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 10, role: 'Abrasive' },
      { ingredientName: 'Hydroxyapatite', percentageW: 8.0, role: 'Remineralization' },
      { ingredientName: 'PEG-8', percentageW: 5.0, role: 'Humectant' },
      { ingredientName: 'Sodium Methyl Cocoyl Taurate', percentageW: 1.5, role: 'Surfactant' },
      { ingredientName: 'Spearmint Oil', percentageW: 1.2, role: 'Flavor' },
      { ingredientName: 'Carbomer 956', percentageW: 0.6, role: 'Thickener' },
      { ingredientName: 'Xanthan Gum', percentageW: 0.5, role: 'Thickener' },
      { ingredientName: 'Phenoxyethanol', percentageW: 0.5, role: 'Preservative' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.3, role: 'Opacifier' },
      { ingredientName: 'Sodium Fluoride', percentageW: 0.25, role: 'Fluoride source' },
      { ingredientName: 'Sodium Hydroxide', percentageW: 0.2, role: 'pH adjuster' },
      { ingredientName: 'Stevia Extract', percentageW: 0.1, role: 'Natural sweetener' },
      { ingredientName: 'Coenzyme Q10', percentageW: 0.03, role: 'Gum health active' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 500, unit: 'RPM', range: { min: 400, max: 700 } },
      { name: 'Temperature', value: 20, unit: '°C', range: { min: 18, max: 24 } },
      { name: 'Mixing Time', value: 60, unit: 'minutes', range: { min: 45, max: 75 } },
      { name: 'Vacuum', value: -0.7, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 950, unit: 'ppm', target: { min: 900, ideal: 1000 }, higherIsBetter: true },
      { name: 'RDA', value: 45, unit: '', target: { max: 70, ideal: 45 } },
      { name: 'Viscosity', value: 100000, unit: 'cP', target: { min: 85000, max: 115000 } },
      { name: 'pH', value: 7.3, unit: '', target: { min: 7.0, max: 7.8 } },
      { name: 'Overall Sensory Score', value: 8.2, unit: '/10', target: { min: 7.5 }, higherIsBetter: true },
      { name: 'Remineralization Index', value: 88, unit: '%', target: { min: 75 }, higherIsBetter: true },
      { name: 'Enamel Hardness Improvement', value: 12, unit: '%', target: { min: 8 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 2.40,
    retailPrice: 14.99,
  },

  // SKU 10: FreshSmile Baking Soda Fresh 6.0oz
  {
    name: 'FreshSmile Baking Soda Fresh 6.0oz',
    code: 'FS-BS-60',
    targetDemographic: 'Adults 40-70, traditional preferences',
    targetGeo: 'North America',
    positioningStatement: 'Old-fashioned freshness, modern protection',
    formulation: [
      { ingredientName: 'Baking Soda', percentageW: 30, role: 'Abrasive / freshness' },
      { ingredientName: 'Water', percentageW: 20, role: 'Solvent' },
      { ingredientName: 'Glycerin', percentageW: 15, role: 'Humectant' },
      { ingredientName: 'Sorbitol', percentageW: 12, role: 'Humectant' },
      { ingredientName: 'Propylene Glycol', percentageW: 8.64, role: 'Humectant' },
      { ingredientName: 'Hydrated Silica', percentageW: 8, role: 'Abrasive' },
      { ingredientName: 'Sodium Lauryl Sulfate', percentageW: 1.2, role: 'Surfactant' },
      { ingredientName: 'Hydrogen Peroxide', percentageW: 1.0, role: 'Whitening' },
      { ingredientName: 'Carboxymethyl Cellulose', percentageW: 1.0, role: 'Binder' },
      { ingredientName: 'Peppermint Oil', percentageW: 0.8, role: 'Flavor' },
      { ingredientName: 'Sodium Monofluorophosphate', percentageW: 0.76, role: 'Fluoride source' },
      { ingredientName: 'Titanium Dioxide', percentageW: 0.5, role: 'Opacifier' },
      { ingredientName: 'Cellulose Gum', percentageW: 0.5, role: 'Binder' },
      { ingredientName: 'Sodium Saccharin', percentageW: 0.3, role: 'Sweetener' },
      { ingredientName: 'Sodium Benzoate', percentageW: 0.3, role: 'Preservative' },
    ],
    processingConditions: [
      { name: 'Mixing Speed', value: 700, unit: 'RPM', range: { min: 500, max: 900 } },
      { name: 'Temperature', value: 23, unit: '°C', range: { min: 20, max: 28 } },
      { name: 'Mixing Time', value: 40, unit: 'minutes', range: { min: 30, max: 50 } },
      { name: 'Vacuum', value: -0.5, unit: 'bar' },
    ],
    outcomes: [
      { name: 'Fluoride Release', value: 800, unit: 'ppm', target: { min: 750 }, higherIsBetter: true },
      { name: 'RDA', value: 110, unit: '', target: { max: 150, ideal: 100 } },
      { name: 'Viscosity', value: 68000, unit: 'cP', target: { min: 55000, max: 80000 } },
      { name: 'pH', value: 8.2, unit: '', target: { min: 7.5, max: 8.5 } },
      { name: 'Overall Sensory Score', value: 6.8, unit: '/10', target: { min: 6.0 }, higherIsBetter: true },
      { name: 'Whitening Shade Change', value: 1.5, unit: 'delta-E', target: { min: 1.0 }, higherIsBetter: true },
      { name: 'Shelf Stability', value: 24, unit: 'months', target: { min: 18 }, higherIsBetter: true },
    ],
    estimatedCOGS: 0.35,
    retailPrice: 3.49,
  },
];

// ============================================================
// TOOTHPASTE INNOVATION PROJECTS — 4 projects
// Datasets are generated dynamically by src/data/projects.ts
// ============================================================

const TOOTHPASTE_PROJECTS: InnovationProject[] = [
  // Project 1: Gen-Z Probiotic Toothpaste
  {
    name: 'Gen-Z Probiotic Toothpaste',
    type: 'new_audience',
    description:
      'Develop a new toothpaste SKU targeting Gen-Z consumers (18-25) who prioritize gut-health, microbiome-friendly, and "clean beauty" positioning. Must be SLS-free, fluoride-optional, Instagram-worthy packaging appeal. Explore hydroxyapatite as fluoride alternative.',
    inputs: [
      { name: 'Hydroxyapatite %', type: 'ingredient_percentage', range: { min: 3, max: 10 }, unit: '%' },
      { name: 'Activated Charcoal %', type: 'ingredient_percentage', range: { min: 0, max: 3 }, unit: '%' },
      { name: 'Aloe Vera Extract %', type: 'ingredient_percentage', range: { min: 0.5, max: 3 }, unit: '%' },
      { name: 'Cocamidopropyl Betaine %', type: 'ingredient_percentage', range: { min: 1, max: 3 }, unit: '%' },
      { name: 'Glycerin %', type: 'ingredient_percentage', range: { min: 18, max: 30 }, unit: '%' },
      { name: 'Xanthan Gum %', type: 'ingredient_percentage', range: { min: 0.3, max: 1.2 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 400, max: 800 }, unit: 'RPM' },
      { name: 'Temperature', type: 'processing_condition', range: { min: 18, max: 28 }, unit: '°C' },
    ],
    outcomes: [
      { name: 'Remineralization Index', unit: '%', direction: 'maximize', importance: 'primary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'primary' },
      { name: 'Viscosity', unit: 'cP', direction: 'target', targetValue: 75000, importance: 'secondary' },
      { name: 'pH', unit: '', direction: 'target', targetValue: 7.0, importance: 'secondary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'tertiary' },
      { name: 'Shelf Stability', unit: 'months', direction: 'maximize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Maximize Remineralization Index above 75%', metric: 'Remineralization Index', goal: 'maximize', targetValue: 75, priority: 1 },
      { description: 'Achieve Sensory Score above 8.0', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 8.0, priority: 2 },
      { description: 'Keep COGS below $1.50/unit', metric: 'COGS per unit', goal: 'minimize', targetValue: 1.50, priority: 3 },
      { description: 'Achieve shelf stability of at least 18 months', metric: 'Shelf Stability', goal: 'maximize', targetValue: 18, priority: 4 },
    ],
    constraints: [
      { description: 'Total formulation must sum to 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
      { description: 'No SLS (0% Sodium Lauryl Sulfate)', type: 'ingredient_limit', parameter: 'SLS', operator: '==', value: 0, unit: '%' },
      { description: 'Hydroxyapatite minimum 5% for efficacy claim', type: 'ingredient_limit', parameter: 'Hydroxyapatite', operator: '>=', value: 5, unit: '%' },
      { description: 'pH between 6.5 and 7.5', type: 'regulatory', parameter: 'pH', operator: 'between', value: [6.5, 7.5] },
      { description: 'Viscosity between 60000 and 90000 cP', type: 'processing', parameter: 'Viscosity', operator: 'between', value: [60000, 90000], unit: 'cP' },
      { description: 'COGS ≤ $1.50/unit', type: 'cost_limit', parameter: 'COGS', operator: '<=', value: 1.50, unit: '$' },
    ],
    dataset: [], // Generated by src/data/projects.ts
  },

  // Project 2: Whitening Boost for FreshSmile Brilliant White
  {
    name: 'Whitening Boost for FreshSmile Brilliant White',
    type: 'performance_optimization',
    description:
      'Improve the whitening efficacy of the existing Brilliant White SKU (FS-BW-35) by at least 30% (from 2.1 to 2.7+ delta-E shade change) while maintaining or improving sensory scores and staying within regulatory limits.',
    baseSKU: 'FS-BW-35',
    inputs: [
      { name: 'Hydrogen Peroxide %', type: 'ingredient_percentage', range: { min: 1.0, max: 3.0 }, unit: '%' },
      { name: 'Alumina %', type: 'ingredient_percentage', range: { min: 3, max: 8 }, unit: '%' },
      { name: 'Hydrated Silica %', type: 'ingredient_percentage', range: { min: 15, max: 25 }, unit: '%' },
      { name: 'Tetrasodium Pyrophosphate %', type: 'ingredient_percentage', range: { min: 1, max: 4 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 500, max: 900 }, unit: 'RPM' },
      { name: 'Mixing Time', type: 'processing_condition', range: { min: 25, max: 50 }, unit: 'min' },
      { name: 'Temperature', type: 'processing_condition', range: { min: 18, max: 25 }, unit: '°C' },
    ],
    outcomes: [
      { name: 'Whitening Shade Change', unit: 'delta-E', direction: 'maximize', importance: 'primary' },
      { name: 'RDA', unit: '', direction: 'target', targetValue: 120, importance: 'primary' },
      { name: 'Fluoride Release', unit: 'ppm', direction: 'target', targetValue: 880, importance: 'secondary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'Enamel Safety Index', unit: '/10', direction: 'maximize', importance: 'secondary' },
      { name: 'Viscosity', unit: 'cP', direction: 'target', targetValue: 75000, importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Maximize whitening shade change to ≥ 2.7 delta-E', metric: 'Whitening Shade Change', goal: 'maximize', targetValue: 2.7, priority: 1 },
      { description: 'Keep RDA below 150 (hard regulatory limit; below 120 preferred)', metric: 'RDA', goal: 'minimize', targetValue: 150, priority: 2 },
      { description: 'Maintain sensory score ≥ 7.5', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 7.5, priority: 3 },
      { description: 'Maintain fluoride release ≥ 850 ppm', metric: 'Fluoride Release', goal: 'maximize', targetValue: 850, priority: 4 },
    ],
    constraints: [
      { description: 'Hydrogen Peroxide ≤ 3.0% (regulatory limit)', type: 'regulatory', parameter: 'Hydrogen Peroxide', operator: '<=', value: 3.0, unit: '%' },
      { description: 'RDA ≤ 150 (ISO 11609)', type: 'regulatory', parameter: 'RDA', operator: '<=', value: 150 },
      { description: 'pH between 5.5 and 7.0 (peroxide stability)', type: 'regulatory', parameter: 'pH', operator: 'between', value: [5.5, 7.0] },
      { description: 'Total abrasive content (Hydrated Silica + Alumina) ≤ 30%', type: 'ingredient_limit', parameter: 'total_abrasive', operator: '<=', value: 30, unit: '%' },
      { description: 'COGS increase ≤ 15% over current ($0.82 → max $0.94)', type: 'cost_limit', parameter: 'COGS', operator: '<=', value: 0.94, unit: '$' },
    ],
    dataset: [],
  },

  // Project 3: Value Engineering FreshSmile Total Care
  {
    name: 'Value Engineering FreshSmile Total Care',
    type: 'cost_reduction',
    description:
      'Reduce the COGS of FreshSmile Total Care (FS-TC-60) by at least 20% (from $0.95 to ≤$0.76/unit) while maintaining all performance claims and sensory attributes within acceptable bounds.',
    baseSKU: 'FS-TC-60',
    inputs: [
      { name: 'Stannous Fluoride %', type: 'ingredient_percentage', range: { min: 0, max: 0.454 }, unit: '%' },
      { name: 'Sodium Fluoride %', type: 'ingredient_percentage', range: { min: 0, max: 0.32 }, unit: '%' },
      { name: 'Hydrated Silica %', type: 'ingredient_percentage', range: { min: 12, max: 20 }, unit: '%' },
      { name: 'Calcium Carbonate %', type: 'ingredient_percentage', range: { min: 0, max: 10 }, unit: '%' },
      { name: 'Glycerin %', type: 'ingredient_percentage', range: { min: 15, max: 25 }, unit: '%' },
      { name: 'Sorbitol %', type: 'ingredient_percentage', range: { min: 15, max: 25 }, unit: '%' },
      { name: 'Zinc Citrate %', type: 'ingredient_percentage', range: { min: 0.5, max: 2.0 }, unit: '%' },
      { name: 'Cocamidopropyl Betaine %', type: 'ingredient_percentage', range: { min: 0, max: 2 }, unit: '%' },
      { name: 'SLS %', type: 'ingredient_percentage', range: { min: 0, max: 2 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 600, max: 1000 }, unit: 'RPM' },
    ],
    outcomes: [
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'primary' },
      { name: 'Fluoride Release', unit: 'ppm', direction: 'target', targetValue: 950, importance: 'primary' },
      { name: 'Anti-gingivitis Efficacy', unit: '%', direction: 'maximize', importance: 'secondary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'target', targetValue: 7.5, importance: 'secondary' },
      { name: 'Viscosity', unit: 'cP', direction: 'target', targetValue: 85000, importance: 'tertiary' },
      { name: 'Shelf Stability', unit: 'months', direction: 'target', targetValue: 24, importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Minimize COGS to ≤ $0.76/unit', metric: 'COGS per unit', goal: 'minimize', targetValue: 0.76, priority: 1 },
      { description: 'Maintain fluoride release ≥ 900 ppm', metric: 'Fluoride Release', goal: 'maximize', targetValue: 900, priority: 2 },
      { description: 'Maintain anti-gingivitis efficacy ≥ 75%', metric: 'Anti-gingivitis Efficacy', goal: 'maximize', targetValue: 75, priority: 3 },
      { description: 'Keep sensory score ≥ 7.0', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 7.0, priority: 4 },
    ],
    constraints: [
      { description: 'Must contain a fluoride source (regulatory requirement)', type: 'regulatory', parameter: 'fluoride_source', operator: '>=', value: 0.01, unit: '%' },
      { description: 'Fluoride release ≥ 850 ppm minimum', type: 'regulatory', parameter: 'Fluoride Release', operator: '>=', value: 850, unit: 'ppm' },
      { description: 'Anti-gingivitis efficacy ≥ 70% (minimum for marketing claim)', type: 'regulatory', parameter: 'Anti-gingivitis Efficacy', operator: '>=', value: 70, unit: '%' },
      { description: 'Sensory score ≥ 6.5 (hard minimum)', type: 'regulatory', parameter: 'Overall Sensory Score', operator: '>=', value: 6.5 },
      { description: 'Shelf stability ≥ 18 months', type: 'regulatory', parameter: 'Shelf Stability', operator: '>=', value: 18, unit: 'months' },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },

  // Project 4: SLS-Free Reformulation of FreshSmile Classic Clean
  {
    name: 'SLS-Free Reformulation of FreshSmile Classic Clean',
    type: 'ingredient_substitution',
    description:
      'Reformulate FreshSmile Classic Clean (FS-CC-60) to be SLS-free in response to consumer demand for gentler formulations. Evaluate Cocamidopropyl Betaine and Sodium Methyl Cocoyl Taurate as replacements. Maintain foaming performance, sensory experience, and cost within 10% of original.',
    baseSKU: 'FS-CC-60',
    inputs: [
      { name: 'SLS %', type: 'ingredient_percentage', range: { min: 0, max: 1.5 }, unit: '%' },
      { name: 'Cocamidopropyl Betaine %', type: 'ingredient_percentage', range: { min: 0, max: 3 }, unit: '%' },
      { name: 'Sodium Methyl Cocoyl Taurate %', type: 'ingredient_percentage', range: { min: 0, max: 2 }, unit: '%' },
      { name: 'Hydrated Silica %', type: 'ingredient_percentage', range: { min: 16, max: 22 }, unit: '%' },
      { name: 'Glycerin %', type: 'ingredient_percentage', range: { min: 10, max: 18 }, unit: '%' },
      { name: 'PEG-8 %', type: 'ingredient_percentage', range: { min: 3, max: 7 }, unit: '%' },
      { name: 'Mixing Speed', type: 'processing_condition', range: { min: 600, max: 1000 }, unit: 'RPM' },
      { name: 'Temperature', type: 'processing_condition', range: { min: 20, max: 28 }, unit: '°C' },
    ],
    outcomes: [
      { name: 'Foam Volume', unit: 'mL', direction: 'target', targetValue: 200, importance: 'primary' },
      { name: 'Overall Sensory Score', unit: '/10', direction: 'maximize', importance: 'primary' },
      { name: 'Fluoride Release', unit: 'ppm', direction: 'target', targetValue: 850, importance: 'secondary' },
      { name: 'Viscosity', unit: 'cP', direction: 'target', targetValue: 82000, importance: 'secondary' },
      { name: 'Skin Irritation Score', unit: '/10', direction: 'minimize', importance: 'secondary' },
      { name: 'COGS per unit', unit: '$', direction: 'minimize', importance: 'tertiary' },
    ],
    objectives: [
      { description: 'Achieve 0% SLS while maintaining foam volume ≥ 180 mL', metric: 'Foam Volume', goal: 'maximize', targetValue: 180, priority: 1 },
      { description: 'Keep sensory score ≥ 7.0 (current: 7.2)', metric: 'Overall Sensory Score', goal: 'maximize', targetValue: 7.0, priority: 2 },
      { description: 'Minimize skin irritation score', metric: 'Skin Irritation Score', goal: 'minimize', priority: 3 },
      { description: 'Keep COGS within 10% of current ($0.42 → max $0.46)', metric: 'COGS per unit', goal: 'minimize', targetValue: 0.46, priority: 4 },
    ],
    constraints: [
      { description: 'SLS = 0% (hard constraint for "SLS-Free" claim)', type: 'ingredient_limit', parameter: 'SLS', operator: '==', value: 0, unit: '%' },
      { description: 'Foam volume ≥ 150 mL (minimum acceptable)', type: 'regulatory', parameter: 'Foam Volume', operator: '>=', value: 150, unit: 'mL' },
      { description: 'COGS ≤ $0.50/unit (hard ceiling)', type: 'cost_limit', parameter: 'COGS', operator: '<=', value: 0.50, unit: '$' },
      { description: 'Fluoride release ≥ 800 ppm', type: 'regulatory', parameter: 'Fluoride Release', operator: '>=', value: 800, unit: 'ppm' },
      { description: 'pH between 6.5 and 7.5', type: 'regulatory', parameter: 'pH', operator: 'between', value: [6.5, 7.5] },
      { description: 'Total surfactant load ≤ 4%', type: 'ingredient_limit', parameter: 'total_surfactant', operator: '<=', value: 4, unit: '%' },
      { description: 'Total formulation = 100%', type: 'formulation', parameter: 'total', operator: '==', value: 100, unit: '%' },
    ],
    dataset: [],
  },
];

// ============================================================
// EXPORT
// ============================================================

export const TOOTHPASTE_CONFIG: CategoryConfig = {
  name: 'Toothpaste',
  ingredients: TOOTHPASTE_INGREDIENTS,
  skus: TOOTHPASTE_SKUS,
  projects: TOOTHPASTE_PROJECTS,
};
